---
# tasks file for ansible

- name: include OS specific install
  include: "install_{{ ansible_os_family | lower }}.yml"      

- name: copy pip requirements.txt file to remote 
  copy:
    src: requirements.txt
    dest: /tmp/requirments.txt

# Check where pip install the packages:
#   python -m site [--user-site]
- name: install ansible using pip
  pip:
    requirements: /tmp/requirments.txt
    state: present
