---
# defaults file for jenkins
jenkins_home: "/apps/jenkins"
jenkins_port: 8080
jenkins_context_path: ""
jenkins_url_external: "http://{{ ansible_hostname }}:{{ jenkins_port }}"

jenkins_name: jenkins
jenkins_svc_name: jenkins

# LTS version
jenkins_version: 2.176.3

jenkins_owner: jenkins
jenkins_group: jenkins

jenkins_backup_dir: /apps/jenkins/backup