---
# tasks file for openjdk

- name: include OS specific install
  include: "install_{{ ansible_os_family | lower }}.yml"

- name: create the /usr/bin/java command symlink 
  file:
    path: "/usr/bin/java"
    src: "{{openjdk_home}}/jdk-{{openjdk_version}}/bin/java"
    owner: "{{ openjdk_owner | default('root')}}"
    group: "{{ openjdk_group | default('root')}}"
    state: link   