---
- hosts: all
  become: true

  tasks:
    - name: download a zip file
      get_url:
        url: "https://github.com/mpt-bootcamp/assets-manager/releases/download/v1.0.0/assets-manager-1.0.0.zip"
        dest: "/tmp/assets-manager.zip"

    - name: unpackage
      unarchive:
        src: "/tmp/assets-manager.zip"
        dest: "/tmp"    
        remote_src: yes
      register: unzip_output

    - name: show unzip output
      debug: 
        var: unzip_output
