---
- hosts: all
  become: true

  tasks:
    - name: Update apt-cache 
      apt: update_cache=yes

    - name: Install apache2
      apt: name=apache2 state=present

    - name: Enable Mod_Rewrite
      command: a2enmod rewrite
      notify: restart apache
    
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
