---
- hosts: all
  become: true

  tasks:
    - name: Update apt-cache 
      apt: update_cache=yes

    - name: Install unzip
      apt: name={{ item }} state=latest
      loop:
        - unzip
        - tree
        - ntp
