---
# tasks file for jenkins

- name: include OS-specific install
  include: "install_{{ ansible_os_family | lower }}.yml"

- name: include OS specific install
  include: "install_{{ ansible_os_family | lower }}.yml"

- name: configure Jenkins
  include: "configure.yml"  



